name: dxf
description: DXF package for Dart developers to create, read, update and delete the data in AutoCAD DXF file - a CAD data file format developed by Autodesk.
version: 1.1.0
homepage: https://github.com/chuyentt/dxf

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
  
  
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  universal_io: ^1.0.1