name: dxf
description: DXF package for Dart developers to create, read, update and delete the data in AutoCAD DXF file - a CAD data file format developed by Autodesk.
version: 2.0.0+2
homepage: https://github.com/chuyentt/dxf

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  universal_io: ^2.0.1
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
